<a href="https://colab.research.google.com/github/bashtavenko/colabs/blob/main/linear_algebra_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Linear algebra basics

In [1]:
#@title Common imports
import numpy as np
import matplotlib.pyplot as plt


# Vectors

In [ ]:
v = np.array([1, 1])
w = np.array([2, 3])

In [ ]:
# Linear combination
print(3*v + 5*w)

# Dot product
v = np.array([1, 2])
w = np.array([4, 5])
print(np.dot(v, w))

# Length (norm or magnitude)
v = np.array([1, 3, 2])
print(np.linalg.norm(v))

# Unit vector
print(v/np.linalg.norm(v))

# Angle between vectors
v = np.array([1, 0])
w = np.array([1, 1])
# 45 degrees 
print(np.rad2deg(np.arccos(np.dot(v, w)/(np.linalg.norm(v)*np.linalg.norm(w)))))

[8 5]
14
3.7416573867739413
[0.26726124 0.80178373 0.53452248]
45.00000000000001


# Matrices

In [4]:
# Dot product
a = np.array([[3, 4], [1, 5], [2, 0]])
b = np.array([[2, 4], [1, 1]])
print (np.dot(a, b))

# Inverse
a = np.array([[2, 3], [4, 7]])
print (np.linalg.inv(a))

[[10 16]
 [ 7  9]
 [ 4  8]]
[[ 3.5 -1.5]
 [-2.   1. ]]
